name: DevSecOps CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  dvwa-setup-and-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Install Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/latest/download/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker-compose --version

      - name: Start DVWA containers
        run: docker-compose up -d

      - name: Wait for DVWA to be ready
        run: sleep 30

      - name: Run Trivy scan on DVWA image
        run: trivy image ghcr.io/digininja/dvwa:latest

      - name: Run OWASP ZAP scan
        run: docker run --rm owasp/zap2docker-stable zap-baseline.py -t http://127.0.0.1:4280

      - name: Tear down containers
        run: docker-compose down

  notify-success:
    runs-on: ubuntu-latest
    needs: dvwa-setup-and-scan
    if: success()
    steps:
      - name: Send Slack Notification (Success)
        run: |
          curl -X POST -H 'Content-type: application/json' \
          --data '{"text":" DevSecOps pipeline for DVWA completed successfully!"}' \
          ${{ secrets.SLACK_WEBHOOK_URL }}

  notify-failure:
    runs-on: ubuntu-latest
    needs: dvwa-setup-and-scan
    if: failure()
    steps:
      - name: Send Slack Notification (Failure)
        run: |
          curl -X POST -H 'Content-type: application/json' \
          --data '{"text":" DevSecOps pipeline for DVWA failed!"}' \
          ${{ secrets.SLACK_WEBHOOK_URL }}

